  main = ".open-next/worker.js"
  name = "personal-portfolio"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  
  [[d1_databases]]
  binding = "DB"
  database_name = "contact-me-personal-portfolio"
  database_id = "5176217d-caa7-49d5-8204-18e736d3a170"

# Environment variables (secrets should be set using 'wrangler secret put')
[vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAB3bEMvn_6FTfB4y"
# Secrets (set using: wrangler secret put TURNSTILE_SECRET_KEY)
# TURNSTILE_SECRET_KEY = "your-secret-key-here"
# DISCORD_WEBHOOK_URL = "your-discord-webhook-ur1-here"
  
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

  # Server-side secrets - set these using wrangler secret put command:
  # wrangler secret put TURNSTILE_SECRET_KEY
  # wrangler secret put DISCORD_WEBHOOK_URL
  # wrangler secret put DISCORD_WEBHOOK_URL