  main = ".open-next/worker.js"
  name = "personal-portfolio"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  
  [[d1_databases]]
  binding = "DB"
  database_name = "contact-me-personal-portfolio"
  database_id = "5176217d-caa7-49d5-8204-18e736d3a170"
  
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

  # Server-side secrets - set these using wrangler secret put command:
  # wrangler secret put TURNSTILE_SECRET_KEY
  # wrangler secret put DISCORD_WEBHOOK_URL
  # wrangler secret put DISCORD_WEBHOOK_URL